# English - Turkish Dictionary

dictionary = {
    
              "a"               : "Bir",
              "abandon"         : "Terk Etmek",
              "ability"         : "Kabiliyet",
              "able"            : "Yapabilmek",
              "about"           : "Hakkında",
              "above"           : "Yukarıda",
              "abroad"          : "Yurt Dışı",
              "absence"         : "Yokluk",
              "absent"          : "Yok",
              "absolute"        : "Kesin",
              "abstract"        : "Öz",
              "abuse"           : "Taciz",
              "abusive"         : "Küfürbaz",
              "academic"        : "Akademik",
              "accept"          : "Kabul Etmek",
              "acceptable"      : "Kabul Edilebilir",
              "access"          : "Giriş",
              "accident"        : "Kaza",
              "accompany"       : "Eşlik Etmek",
              "according"       : "Göre",
              "account"         : "Hesap",
              "accountant"      : "Muhasebeci",
              "accurate"        : "Doğru",
              
              "baby"            : "Bebek",
              "bachelor degree" : "Lisans Derecesi",
              "back"            : "Geri",
              "backboard"       : "Sedye",
              "backhand"        : "Ters Vuruş",
              "backward"        : "Geriye",
              "bacterium"       : "Bakteri",
              "bad"             : "Kötü",
              "badly"           : "Kötü",
              "bag"             : "Sırt Çantası",
              "baggage"         : "Bagaj",
              "bake"            : "Pişirmek",
              "balance"         : "Denge",
              "ball"            : "Top",
              "band"            : "Grup",
              "bandage"         : "Bandaj",
              "bang"            : "Patlama",
              "bank"            : "Banka",
              "banker"          : "Bankacı",
              "bankrupt"        : "İflas Etmiş",
              "banruptcy"       : "İflas",
              
              "cage"            : "Kafes",
              "cake"            : "Kek", 
              "calculate"       : "Hesaplamak",
              "calculation"     : "Hesaplama",
              "calender"        : "Takvim",
              "calf"            : "Buzağı",
              "call"            : "Aramak",
              "calm"            : "Sakin",
              "camera"          : "Kamera",
              "camp"            : "Kamp",
              "campaign"        : "Kampanya",
              "campus"          : "Campus",
              "can"             : "Yapabilmek",
              "cancel"          : "İptal Etmek",
              "cancer"          : "Kanser",
              "candidate"       : "Aday",
              "candy"           : "Şeker",
              "cap"             : "Kapak",
              "capable"         : "Yetenekli",
              "capacity"        : "Kapasite",
              "capital"         : "Başkent",
              "captain"         : "Kaptan",
              "capture"         : "Ele Geçirmek",
              "car"             : "Araba",
              "carbon Dioxide"  : "Karbondioksit",
              "carbon Monoxide" : "Karbonmonoksit",
                  
              "dad"             : "Baba",
              "daily"           : "Günlük",
              "dam"             : "Baraj",
              "damage"          : "Hasar",
              "damages"         : "Tazminat",
              "damp"            : "Nemli",
              "dance"           : "Dans",
              "danger"          : "Tehlike",
              "dangerous"       : "Tehlikeli",
              "dare"            : "Cesaret Etmek",
              "dark"            : "Karanlık",
              "data"            : "Veri",
              "date"            : "Tarih",
              "daughter"        : "Kız Evlat",
              "dawn"            : "Şafak",
              "day"             : "Gün",
              "dead"            : "Ölü",
              "deaf"            : "Sağır",
              "deal"            : "Anlaşma",
              "dear"            : "Sayın, Sevgili",
              "death"           : "Ölüm",
              
              
              "e-mail"          : "E-posta",
              "each"            : "Her Biri",
              "eager"           : "İsteklli",
              "ear"             : "Kulak",
              "earlier"         : "Daha Erken",
              "earlobe"         : "Kulak Memesi",
              "early"           : "Erken",
              "earn"            : "Kazanmak",
              "earth"           : "Dünya",
              "ease"            : "Kolaylaştırmak",
              "east"            : "Doğu",
              "easy"            : "Kolay",
              "easygoing"       : "Uyumlu",
              "eat"             : "Yemek",
              "ecology"         : "Ekoloji",
              "economic"        : "Ekonomik",
              "economics"       : "Ekonomi Bilimi",
              "economist"       : "İktisatçı",
              "economy"         : "Ekonomi",
              "ecosystem"       : "Ekosistem",
              "edge"            : "Kenar",
              "edit"            : "Düzenle",
              "edition"         : "Baskı",
              
              "fabric"          : "Kumaş",
              "face"            : "Yüz",
              "fact"            : "Gerçek",
              "factor"          : "Faktör",
              "factory"         : "Fabrika",
              "faculty"         : "Fakülte",
              "fail"            : "Başarısız",
              "failure"         : "Başarısızlık",
              "faint"           : "Baygın",
              "fair"            : "Fuar",
              "faith"           : "İnanç",
              "fake"            : "Sahte",
              "fall"            : "Sonbahar",
              "false"           : "Yanlış",
              "fame"            : "Şöhret",
              "familiar"        : "Tanıdık",
              "family"          : "Aile",
              "famous"          : "Tanınmış",
              "fan"             : "Yelpaze",
              "fancy"           : "Fantezi",
              "far"             : "Uzak",
              
              "gain"            : "Kazanç",
              "gallon"          : "Galon",
              "game"            : "Oyun",
              "gap"             : "Boşluk",
              "garage"          : "Garaj",
              "garbage"         : "Çöp",
              "garden"          : "Bahçe",
              "gas"             : "Gas",
              "gate"            : "Kapı",
              "gather"          : "Toplamak",
              "gay"             : "Eşcinsel",
              "gear"            : "Vites",
              "gender"          : "Cinsiyet",
              "gene"            : "Gen",
              "general"         : "Genel",
              "generally"       : "Genellikle",
              "generate"        : "Üretmek",
              "generation"      : "Nesil",
              "generosity"      : "Cömertlik",
              "generous"        : "Cömert",
              "gentle"          : "Nazik",
              "gentleman"       : "Beyefendi",
              "genuine"         : "Hakiki",
              "geography"       : "Coğrafya",
              "geothermal"      : "Jeotermal",
              "get"             : "Almak",
              "giant"           : "Dev",
              
              
              "habit"           : "Alışkanlık",
              "habitat"         : "Doğal Ortam",
              "hail"            : "Selamlamak",
              "hair"            : "Saç",
              "half"            : "Half",
              "half time"       : "İlk Yarı",
              "hammer"          : "Çekiç",
              "hand"            : "El",
              "handle"          : "Üstesinden Gelmek",
              "handsome"        : "Yakışıklı",
              "handwriting"     : "El Yazısı",
              "hang"            : "Asmak",
              "happen"          : "Olmak, Meydana Gelmek",
              "happy"           : "Mutlu",
              "harbor"          : "Liman",
              "hard"            : "Zor",
              "hardware"        : "Donanım",
              "harm"            : "Zarar",
              "harsh"           : "Sert",
              "harvest"         : "Hasat",
              "hat"             : "Şapka",
              
              
              "I"               : "Ben",
              "ice"             : "Buz",
              "idea"            : "Fikir",
              "ideal"           : "İdeal",
              "identical"       : "Özdeş",
              "identification"  : "Kimlik",
              "identify"        : "Belirlemek",
              "if"              : "Eğer",
              "ignore"          : "Göz Ardı Etmek",
              "ill"             : "Hasta",
              "illegal"         : "Yasa Dışı",
              "illness"         : "Hastalık",
              "illustrate"      : "Resimlemek, Gözünde Canlandırmak",
              "image"           : "Görüntü",
              "imaginary"       : "Hayali",
              "imagination"     : "Hayal Gücü",
              "imaginative"     : "Yaratıcı",
              "imagine"         : "Hayal Etmek",
              "imitate"         : "Taklit Etmek",
              "immediate"       : "Acil",
              "immigrant"       : "Göçmen",
              "immoral"         : "Ahlaksız",
              "impact"          : "Etki",
              "impatience"      : "Sabırsızlık",
              "impatient"       : "Sabırsız",
              "import"          : "İthalat",
              
              
              "jacket"          : "Ceket",
              "jail"            : "Hapis",
              "jam"             : "Reçel",
              "jar"             : "Kavanoz",
              "jaw"             : "Çene",
              "jealous"         : "Kıskanç",
              "jealousy"        : "Kıskançlık",
              "jelly"           : "Jöle",
              "jet"             : "Jet",
              "jet engine"      : "Jet Motoru",
              "jewel"           : "Mücevher",
           
}
keyword = input()
print(dictionary[keyword])
 